title: <p align="center"> Keya Bhattacharjee </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a>
  <a href="https://www.linkedin.com/in/keyabhattacharjee/">LinkedIn</a> |
  <a href="https://github.com/KeyaBhattacharjee">GitHub</a>
  
  <br>   
  I am learning AI and ML from Upgrad.
  I'm working on Data Science projects so that I can upscale my skills.
  <br>
  </p>



theme: jekyll-theme-minimal
